#!/bin/bash
set -e

PREVIOUS_COMMIT=$1

if [ -z "$PREVIOUS_COMMIT" ]; then
  echo "❌ Error: Previous commit hash required for rollback."
  exit 1
fi

echo "Starting Rollback to commit: $PREVIOUS_COMMIT..."

# 1. Revert Git state
git reset --hard "$PREVIOUS_COMMIT"

# 2. Re-install dependencies and build the old reliable code
cd server
npm ci
npm run build

# 3. Re-generate Prisma Client
npx prisma generate

# 4. Restart PM2 Cluster
pm2 reload ecosystem.config.js --env production

echo "✅ Rollback completed. System restored to $PREVIOUS_COMMIT."

# NOTE: Database rollbacks are complex. If migrations broke the DB schema, 
# you should manually restore the backup generated by `backup.sh`.
echo "⚠️  NOTE: Database schema has NOT been automatically downgraded."
echo "If the database is corrupted, manually restore the latest file in /var/backups/restaurant-pos/"
